/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as UeberRouteImport } from './routes/ueber'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as FuerWenRouteImport } from './routes/fuer-wen'
import { Route as BgmRouteImport } from './routes/bgm'
import { Route as AngeboteRouteImport } from './routes/angebote'
import { Route as IndexRouteImport } from './routes/index'

const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberRoute = UeberRouteImport.update({
  id: '/ueber',
  path: '/ueber',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const FuerWenRoute = FuerWenRouteImport.update({
  id: '/fuer-wen',
  path: '/fuer-wen',
  getParentRoute: () => rootRouteImport,
} as any)
const BgmRoute = BgmRouteImport.update({
  id: '/bgm',
  path: '/bgm',
  getParentRoute: () => rootRouteImport,
} as any)
const AngeboteRoute = AngeboteRouteImport.update({
  id: '/angebote',
  path: '/angebote',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/angebote': typeof AngeboteRoute
  '/bgm': typeof BgmRoute
  '/fuer-wen': typeof FuerWenRoute
  '/kontakt': typeof KontaktRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber': typeof UeberRoute
  '/workshops': typeof WorkshopsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/angebote': typeof AngeboteRoute
  '/bgm': typeof BgmRoute
  '/fuer-wen': typeof FuerWenRoute
  '/kontakt': typeof KontaktRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber': typeof UeberRoute
  '/workshops': typeof WorkshopsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/angebote': typeof AngeboteRoute
  '/bgm': typeof BgmRoute
  '/fuer-wen': typeof FuerWenRoute
  '/kontakt': typeof KontaktRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber': typeof UeberRoute
  '/workshops': typeof WorkshopsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/angebote'
    | '/bgm'
    | '/fuer-wen'
    | '/kontakt'
    | '/sitemap.xml'
    | '/ueber'
    | '/workshops'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/angebote'
    | '/bgm'
    | '/fuer-wen'
    | '/kontakt'
    | '/sitemap.xml'
    | '/ueber'
    | '/workshops'
  id:
    | '__root__'
    | '/'
    | '/angebote'
    | '/bgm'
    | '/fuer-wen'
    | '/kontakt'
    | '/sitemap.xml'
    | '/ueber'
    | '/workshops'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AngeboteRoute: typeof AngeboteRoute
  BgmRoute: typeof BgmRoute
  FuerWenRoute: typeof FuerWenRoute
  KontaktRoute: typeof KontaktRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UeberRoute: typeof UeberRoute
  WorkshopsRoute: typeof WorkshopsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber': {
      id: '/ueber'
      path: '/ueber'
      fullPath: '/ueber'
      preLoaderRoute: typeof UeberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuer-wen': {
      id: '/fuer-wen'
      path: '/fuer-wen'
      fullPath: '/fuer-wen'
      preLoaderRoute: typeof FuerWenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bgm': {
      id: '/bgm'
      path: '/bgm'
      fullPath: '/bgm'
      preLoaderRoute: typeof BgmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angebote': {
      id: '/angebote'
      path: '/angebote'
      fullPath: '/angebote'
      preLoaderRoute: typeof AngeboteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AngeboteRoute: AngeboteRoute,
  BgmRoute: BgmRoute,
  FuerWenRoute: FuerWenRoute,
  KontaktRoute: KontaktRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UeberRoute: UeberRoute,
  WorkshopsRoute: WorkshopsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
